; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;; ======================================
;; Common envs
;; ======================================
[common]

ota_pass = ${sysenv.SMARTHOME_OTA_PASSWD}

build_flags_home =
  -D _WIFI_SSID_=\"${sysenv.SMARTHOME_WIFI_SSID}\"
  -D _WIFI_PWD_=\"${sysenv.SMARTHOME_WIFI_PWD}\"
  -D _MQTT_BROKER_=\"${sysenv.SMARTHOME_MQTT_BROKER}\"

build_flags_office =
  -D _WIFI_SSID_=\"${sysenv.SMARTHOME_WIFI_SSID_OFFICE}\"
  -D _WIFI_PWD_=\"${sysenv.SMARTHOME_WIFI_PWD_OFFICE}\"
  -D _MQTT_BROKER_=\"${sysenv.SMARTHOME_MQTT_BROKER_OFFICE}\"

build_flags = ${this.build_flags_home}

;; ======================================
;; Shared envs
;; ======================================
[env]
framework = arduino

lib_deps = 
;	bblanchon/ArduinoJson @ ~6.18.5
	bblanchon/ArduinoJson @ ~6.21.2
	knolleary/PubSubClient @ ~2.8

build_flags = 
  -D _OTA_PASSWD_=\"${common.ota_pass}\"


;; ======================================
;; ESP8266 RELEASE OTA (default)
;; ======================================
[env:RELEASE_OTA_esp8266]
platform = espressif8266
board = d1_mini

hostname = rempowercntl1
area = home

monitor_port = COM5
monitor_speed = 115200

upload_protocol = espota
; upload_port = 192.168.1.178
upload_port = ${this.hostname}
upload_flags = --auth=${common.ota_pass}

build_flags = 
  -D _SN_RELEASE_BUILD_
  -D _HOST_NAME_=\"${this.hostname}\"
  -D _AREA_=\"${this.area}\"
  ${env.build_flags}
  ${common.build_flags}


;; ======================================
;; ESP8266 RELEASE Serial
;; ======================================
[env:RELEASE_COM_esp8266]
platform = espressif8266
board = d1_mini

hostname = rempowercntl1
area = home

monitor_port = COM6
monitor_speed = 115200

upload_port = COM6
upload_speed = 200000

build_flags = 
	-D _SN_RELEASE_BUILD_
  -D _HOST_NAME_=\"${this.hostname}\"
  -D _AREA_=\"${this.area}\"
  ${env.build_flags}
  ${common.build_flags}
  -D DEBUG_ESP_PORT=Serial
  -D DEBUG_ESP_WIFI


;; ======================================
;; ESP8266 TEST Serial
;; ======================================
[env:TESTING_COM_esp8266]
platform = espressif8266
board = d1_mini

hostname = rempowercntl1_test
area = home

monitor_port = COM5
monitor_speed = 115200

upload_port = COM5
upload_speed = 200000

build_flags = 
	-D _SN_TEST_BUILD_
  -D _HOST_NAME_=\"${this.hostname}\"
  -D _AREA_=\"${this.area}\"
  ${env.build_flags}
  ${common.build_flags}
  -D DEBUG_ESP_PORT=Serial
  -D DEBUG_ESP_WIFI


;; ======================================
;; ESP32 RELEASE Serial
;; ======================================
[env:RELEASE_COM_esp32dv]
platform = espressif32@^6.4.0
board = wemos_d1_mini32


hostname = rempowercntl1
area = home

monitor_port = COM5
monitor_speed = 115200

upload_port = COM5
upload_speed = 200000

build_flags = 
	-D _SN_RELEASE_BUILD_
  -D _HOST_NAME_=\"${this.hostname}\"
  -D _AREA_=\"${this.area}\"
  ${env.build_flags}
  ${common.build_flags}
  -D DEBUG_ESP_PORT=Serial
  -D DEBUG_ESP_WIFI

